---
- name: Converge
  hosts: all
  become: true

  vars:
    # Testing is outside ec2, so must define mode accordingly
    cwa_mode: onPremise

  pre_tasks:
    # Ensure region is configured so that service will start
    - name: Create .aws directory
      file:
        path: /root/.aws
        state: directory
        mode: 0644

    - name: Create aws config file
      copy:
        dest: /root/.aws/config
        mode: 0644
        content: |
          [AmazonCloudWatchAgent]
          region = us-west-1

  roles:
    - role: newtonne.cloudwatchagent
